[project]
name = "ouroboros-quant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "巫瀚东", email = "16187019+wu3134@user.noreply.gitee.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
ouroboros-quant = "ouroboros_quant:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
